#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp /mnt/c/Users/USER/Documents/FYP/03_06_22_NN01.pb .

# ------------------------------------------------------------------------------
